apiVersion: apps/v1
kind: Deployment
metadata:
  name: postdep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postdep
        image:  yousufabdulilah/postgresbk:v3
        env: 
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                key: password
                name: postdb
        
        ports:
        - containerPort: 5432
        volumeMounts:
          - mountPath: /var/lib/postgresql/data  
            name: poststorage
            subPath: postgres-dat
      volumes:
        - name: poststorage
          persistentVolumeClaim:
            claimName: postpvc