apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postpvc
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  storageClassName: postgressc
  accessModes:
    - ReadWriteOnce
